# Copyright (C) 2018 Betalo AB

ignored = [
  "google.golang.org/appengine/*",
]

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  revision = "bc14601d1bd56421dd60f561e6052c9ed77f9daf"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/lib/pq"
  revision = "88edab0803230a3898347e77b474f8c1820a1f20"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
